version: "3.3"

volumes:
  postgres:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: server
    env_file:
      - ./env/server.env
    ports:
      - 3000:3000
    volumes:
      - ./public:/usr/local/src/workspace/public/
