name:                interview
version:             0.1.0.0

author:              Todd Mohney
category:            Web
copyright:           2020 Todd Mohney
description:         I'm a interview project
github:              toddmohney/hasura-interview
license:             MIT
maintainer:          toddmohney@gmail.com
synopsis:            I'm a interview project

default-extensions:
- DefaultSignatures
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- RecordWildCards
- TemplateHaskell
- TypeApplications
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fhide-source-paths
- -fno-warn-warnings-deprecations
- -freverse-errors
- -fwarn-unused-binds
- -fwarn-unused-imports
- -fwarn-unused-matches

dependencies: []

library:
  source-dirs: ./lib
  exposed-modules:
  - Interview
  - Interview.Class.Concurrency
  - Interview.Class.FastLogger
  - Interview.Class.Instrumentation
  - Interview.Class.Time
  - Interview.Class.WebSocket
  - Interview.Errors
  - Interview.Environment
  dependencies:
  - base
  - bytestring
  - ekg-core
  - exceptions
  - fast-logger
  - filepath
  - http-api-data
  - http-client
  - http-media
  - http-types
  - lens
  - lens-aeson
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - persistent-template
  - servant
  - servant-blaze
  - servant-server
  - text
  - time
  - unordered-containers
  - uuid
  - websockets

executables:
  server:
    main:                Main.hs
    source-dirs:         ./src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    dependencies:
    - aeson
    - base
    - blaze-html
    - blaze-markup
    - bytestring
    - ekg-core
    - exceptions
    - fast-logger
    - interview
    - lens
    - mtl
    - servant-blaze
    - servant-ekg
    - servant-server
    - servant-websockets
    - text
    - unordered-containers
    - warp
    - wai
    - wai-cors
    - wai-extra
    - websockets

tests:
  hspecs:
    main:                Main.hs
    source-dirs:
    - ./test
    ghc-options:
    - -fno-warn-unused-imports
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - text
    - unordered-containers
    - interview
